[project]
name = "ps-solve-py"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "pandas>=2.3.0",
    "pip>=25.1.1",
    "requests>=2.32.4",
    "tqdm>=4.67.1",
    "uvicorn>=0.34.2",
]
